# Generated by Django 6.0.3 on 2026-04-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
