# Generated by Django 6.0.3 on 2026-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_todo_time_notification_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='time_notification',
        ),
        migrations.AddField(
            model_name='todo',
            name='notif_time',
            field=models.DateTimeField(null=True),
        ),
    ]
