# Generated by Django 6.0.3 on 2026-04-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_todo_time_notification_todo_notif_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='notif_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='time_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
